# frozen_string_literal: true

source "https://rubygems.org"
ruby "2.7.6"
gem "algorithms"
gem "jbuilder", "~> 2.5"
gem "jquery-rails"
gem "linked-list"
gem "nokogiri"
gem "puma", "~> 4.3"
gem "rails", "~> 5.0.0", ">= 5.0.0.1"
gem "sass-rails", "~> 5.0"
gem 'sqlite3', '~> 1.3.13'
gem "turbolinks", "~> 5"
gem "uglifier", ">= 1.3.0"
group :development, :test do
  gem "byebug", platform: :mri
  gem 'rubocop'
end
group :development do
  gem "listen", "~> 3.0.5"
  gem "web-console"
end
gem "bootstrap-sass"
gem "devise"
gem "high_voltage"
gem "pundit"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
group :development do
  gem "better_errors"
  gem "rails_layout"
end
group :development, :test do
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
end
group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "launchy"
  gem "selenium-webdriver"
end
